trigger:
- main

parameters:
  - name: environment
    type: string
    default: dev
    values: [test, dev, prod]

variables:
  - name: resourceGroupName
    value: '${{ parameters.environment }}-rg-dl'
  - name: location
    value: 'westeurope'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    azureResourceManagerConnection: 'Azure-Sub-Conn'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/main.bicep'
    deploymentMode: 'Incremental'