trigger:
- main

parameters:
  - name: environment
    type: string
    default: dev
    values:
      - test
      - dev
      - prod
  - name: subscriptionId
    type: string
    default: ''

variables:
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: resourceGroupName
    value: '${{ parameters.environment }}-rg-dl'
  - name: location
    value: 'westeurope'
  - name: templateFile
    value: '$(Build.SourcesDirectory)/main.bicep'

pool:
  vmImage: '$(vmImageName)'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'